name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Upload
        env:
          AWS_DEPLOYER_ACCESS_KEY_ID : ${{ secrets.AWS_DEPLOYER_ACCESS_KEY_ID }}
          AWS_DEPLOYER_ACCESS_KEY_SECRET : ${{ secrets.AWS_DEPLOYER_ACCESS_KEY_SECRET }}
          AWS_DEPLOYER_BUCKET_NAME : ${{ secrets.AWS_DEPLOYER_BUCKET_NAME }}
        run: yarn release